# Site settings
title: JoyRest
email: bouda.petr@gmail.com
baseurl: ""
url: "http://www.joyrest.org"
github_username: petrbouda

# Build settings
markdown: kramdown

# Joyrest Versions
joyrest_release: 1.1
joyrest_snapshot: 1.2-SNAPSHOT