# Site settings
title: JoyRest
email: bouda.petr@gmail.com
baseurl: ""
url: "http://petrbouda.github.io/joyrest"
github_username: petrbouda

# Build settings
markdown: kramdown

# Joyrest Versions
joyrest_release: 1.3
joyrest_snapshot: 1.4-SNAPSHOT